---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 192.168.178.53:80/images/debian
    tag: latest
    insecure_registries: ["192.168.178.53:80"]
    username: admin
    password: Harbor12345
inputs:
  - name: concourse-git
run:
  path: concourse-git/tasks/deploy-image/task.sh
