---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 192.168.178.58:80/security-in/webserver
    tag: latest
    insecure_registries: ["192.168.178.58:80"]
    username: admin
    password: Harbor12345

inputs:
  - name: concourse-git

run:
  path: concourse-git/tasks/deploy-image_security-in/task.sh
