---
resources:
  - name: harbor-lab
    type: docker-image
    source:
      repository: 192.168.178.58:80/lab/webserver
      tag: latest
      insecure_registries: ["192.168.178.58:80"]
      username: admin
      password: Harbor12345

  - name: concourse-git
    type: git
    source:
      uri: https://github.com/SKornweih/BA-Scripte/
      branch: master

jobs:
  - name: build-push-container-lab
    serial: true
    plan:
    - get: concourse-git
      trigger: true
    - put: harbor-lab
      params:
        build: concourse-git/

  - name: check-lab-container-security
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "build-push-container-lab"
    - task: start-and-check-with-clair
      file: concourse-git/tasks/check-lab-container-security/task.yml

  - name: deploy-container-lab
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "check-lab-container-security"
    - task: deploy-container-lab
      file: concourse-git/tasks/deploy-image-lab/task.yml
  
  - name: check-lab-container-running
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "deploy-container-lab"
    - task: check-lab-container-running
      file: concourse-git/tasks/check-lab-container-running/task.yml

  - name: deploy-container-prod
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "check-lab-container-running"
    - task: deploy-container-prod
      file: concourse-git/tasks/deploy-image-prod/task.yml

  - name: check-prod-container-running
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "deploy-container-prod"
    - task: check-lab-container-running
      file: concourse-git/tasks/check-prod-container-running/task.yml
