---
resources:
  - name: harbor
    type: docker-image
    source:
      repository: 192.168.178.53:80/bachelor2020/webserver
      tag: latest
      insecure_registries: ["192.168.178.53:80"]
      username: admin
      password: Harbor12345

  - name: concourse-git
    type: git
    source:
      uri: https://github.com/SKornweih/BA-Scripte/
      branch: master

jobs:
  - name: build-container
    serial: true
    plan:
    - get: concourse-git
      trigger: true
    - task: build-container
      file: concourse-git/tasks/build-container/task.yml

  - name: publish-container
    serial: true
    plan:
    - get: concourse-git
      trigger: true
      passed:
    - "build-container"
    - task: publish-container
      file: concourse-git/tasks/publish-container/task.yml

  - name: deploy-image
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "publish-container"
    - task: deploy-image
      file: concourse-git/tasks/deploy-image/task.yml
