---
resources:
  - name: harbor
    type: docker-image
    source:
      repository: 192.168.178.53:80/bachelor2020/webserver
      tag: latest
      insecure_registries: ["192.168.178.53:80"]
      username: admin
      password: Harbor12345

  - name: concourse-git
    type: git
    source:
      uri: https://github.com/SKornweih/BA-Scripte/
      branch: master

jobs:
  - name: build-and-publish-container
    serial: true
    plan:
    - get: concourse-git
      trigger: true
    - put: harbor
      params:
        build: concourse-git/

  - name: deploy-image
    public: false
    plan:
      - get: concourse-git
        trigger: true
        passed:
          - "build-and-publish-container"
      - task: deploy-image
        file: concourse-git/tasks/deploy-image/task.yml
