---
resources:
  - name: harbor-security-in
    type: docker-image
    source:
      repository: 192.168.178.58:80/security-in/webserver
      tag: latest
      insecure_registries: ["192.168.178.58:80"]
      username: admin
      password: Harbor12345

  - name: concourse-git
    type: git
    source:
      uri: https://github.com/SKornweih/BA-Scripte/
      branch: master

jobs:
  - name: build-and-publish-container-security-in
    serial: true
    plan:
    - get: concourse-git
      trigger: true
    - put: harbor-security-in
      params:
        build: concourse-git/

  - name: check-security-in
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "build-and-publish-container-security-in"
    - task: deploy-image
      file: concourse-git/tasks/check-security-in/task.yml

  - name: deploy-image-security-in
    public: false
    plan:
    - get: concourse-git
      trigger: true
      passed:
        - "check-security-in"
    - task: deploy-image
      file: concourse-git/tasks/deploy-image_security-in/task.yml
