---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 192.168.178.58:80/concourse_container/concourse_container
    tag: latest
    insecure_registries: ["192.168.178.58:80"]
    username: admin
    password: Harbor12345

inputs:
  - name: concourse-git

run:
  path: concourse-git/tasks/check-lab-container-security/task.sh
